version: "3"
services:
    mongodb:
        container_name: leaderboard-mongo
        image: "mongo:4"
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pfL5VWkf
            - MONGO_INITDB_DATABASE=my_game
        networks:
            - leaderboard-system
    redis-server:
        container_name: leaderboard-redis
        image: "redis:4.0.11"
        ports:
            - "6379:6379"
        networks:
            - leaderboard-system
    express-app:
        container_name: leaderboard
        build: ./
        ports:
            - "8080:8080"
        environment:
            - REDIS_HOST=redis-server
            - REDIS_PORT=6379
            - MONGODB_HOST=mongodb
            - MONGODB_PORT=27017
            - MONGODB_NAME=my_game
        depends_on:
            - redis-server
            - mongodb
        networks:
            - leaderboard-system

networks:
    leaderboard-system:
        driver: bridge
